before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Lo6GtqAt3eH1DOqXS1nVZ4UAN9dZzMuHYZ6d9tJT4xHHuR/VOrkyxhneaZOTvH3vXbHWZohF6+iV8NmxywBRdHXOS0EjAeW7OKINv6MgshkwiiD0/SkQROD+EvpseqyMlOF1LWburWk0M7J0lMkedTBxPQYIEnv77cF0qh6+zKXIFeqWtmx+kIRzuB4fY4FPdmz/6soqImkiQ45sHdq+Zf8p95QMWziBtkXZLkVIHX78bk9cQdxvc7yDYTnUHjB/HRnpHrrPJTl/9lGPuneif5PpKkskeoRZ4G5nNwXPsxEtVVHGYzubLNHjyoOugjYm3PtCBD1UvCtFsF5kS3fv7gP0hI2HNbNzAXp80L6gde7QpGc2GDauih8CJ3PlvZkCp+8sjCPNPFWV2EKx5CG8STEnyDdjdJo2EeGOmydDmT4KI96K77xGl0lHl7ETCryB1m+J7DrDZCXsai1nCbRqgsin5WsnzjS7W82l31XMCi1S/RgsLLrG0SivkLadM7nqElqcVQwsMKfpyk+NvKT48kL2Fx2+GcWsr6vn8FJWG2GxQhFwxF7arQYgjyAvwKojCN7qDUOIkWASOZAf0yB+680WyLp9WEInjkfCeKda7PlTjiO8iVyWYPMB+OHLddc/wAIUALRU27B9zrpcJ/AN6a9j9N5/u6+nwHk36yeVHLE= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
